FROM node:20.17.0

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY . .

RUN npm run build

RUN cp -r .next/static .next/standalone/.next/
RUN cp -r public .next/standalone/

ENV PORT=4000
ENV HOSTNAME=0.0.0.0

EXPOSE 4000

WORKDIR /app/.next/standalone

CMD ["node", "server.js"]