import { test, expect } from './utils/test-utils';
import { testUsers, testData } from './utils/test-utils';

test.describe('Mind Maps', () => {
  test.beforeEach(async ({ page, pageActions }) => {
    // Sign in before each test
    await pageActions.signIn(testUsers.student.email, testUsers.student.password);
    await page.goto('/tools/mind-maps');
  });

  test.describe('Page Layout', () => {
    test('should display mind maps interface', async ({ page }) => {
      // Check for main page elements
      await expect(page.locator('text=Mind Maps')).toBeVisible();
      await expect(page.locator('text=Visualize your thoughts')).toBeVisible();
      
      // Check for main action buttons
      await expect(page.locator('text=Create Mind Map')).toBeVisible();
      await expect(page.locator('text=AI Generate')).toBeVisible();
    });

    test('should display mind map list', async ({ page }) => {
      // Check for mind maps section
      await expect(page.locator('text=My Mind Maps')).toBeVisible();
      
      // Check for mind map list container
      const mindMapList = page.locator('[data-testid="mindmap-list"], .mindmap-list');
      await expect(mindMapList).toBeVisible();
    });

    test('should display search functionality', async ({ page }) => {
      // Check for search input
      await expect(page.locator('[data-testid="search-input"], input[placeholder*="search"]')).toBeVisible();
    });
  });

  test.describe('Mind Map Creation', () => {
    test('should create new mind map manually', async ({ page }) => {
      // Click create mind map button
      await page.click('text=Create Mind Map');
      
      // Fill in mind map details
      await page.fill('[name="title"]', testData.mindMap.title);
      await page.fill('[name="description"]', testData.mindMap.description);
      await page.selectOption('[name="layout"]', 'radial');
      await page.selectOption('[name="theme"]', 'default');
      
      // Submit the form
      await page.click('text=Create Mind Map');
      
      // Check if mind map is created
      await expect(page.locator('text=Test Mind Map')).toBeVisible();
    });

    test('should create mind map with AI', async ({ page }) => {
      // Click AI generate button
      await page.click('text=AI Generate');
      
      // Fill in generation form
      await page.fill('[name="title"]', 'AI Generated Mind Map');
      await page.fill('[name="description"]', 'A mind map generated by AI');
      await page.fill('[name="topic"]', 'Machine Learning');
      await page.fill('[name="maxNodes"]', '10');
      await page.fill('[name="additionalContext"]', 'Focus on basic concepts');
      
      // Submit the form
      await page.click('text=Generate Mind Map');
      
      // Wait for generation to complete
      await page.waitForSelector('text=Mind Map Generated', { timeout: 60000 });
      
      // Check if mind map is created
      await expect(page.locator('text=AI Generated Mind Map')).toBeVisible();
    });

    test('should handle different layouts', async ({ page }) => {
      const layouts = ['radial', 'hierarchical', 'organic'];
      
      for (const layout of layouts) {
        // Click create mind map button
        await page.click('text=Create Mind Map');
        
        // Fill in details
        await page.fill('[name="title"]', `Test ${layout} layout`);
        await page.fill('[name="description"]', `Testing ${layout} layout`);
        await page.selectOption('[name="layout"]', layout);
        
        // Create mind map
        await page.click('text=Create Mind Map');
        
        // Check if mind map is created
        await expect(page.locator(`text=Test ${layout} layout`)).toBeVisible();
      }
    });

    test('should handle different themes', async ({ page }) => {
      const themes = ['default', 'dark', 'colorful'];
      
      for (const theme of themes) {
        // Click create mind map button
        await page.click('text=Create Mind Map');
        
        // Fill in details
        await page.fill('[name="title"]', `Test ${theme} theme`);
        await page.fill('[name="description"]', `Testing ${theme} theme`);
        await page.selectOption('[name="theme"]', theme);
        
        // Create mind map
        await page.click('text=Create Mind Map');
        
        // Check if mind map is created
        await expect(page.locator(`text=Test ${theme} theme`)).toBeVisible();
      }
    });

    test('should handle AI generation errors', async ({ page }) => {
      // Mock AI service error
      await page.route('**/api/mindmaps/generate/**', route => {
        route.fulfill({
          status: 500,
          body: JSON.stringify({ error: 'AI service unavailable' })
        });
      });
      
      // Try to generate mind map
      await page.click('text=AI Generate');
      await page.fill('[name="topic"]', 'Test Topic');
      await page.click('text=Generate Mind Map');
      
      // Check for error message
      await expect(page.locator('text=AI service unavailable')).toBeVisible();
    });

    test('should validate form inputs', async ({ page }) => {
      // Try to submit empty form
      await page.click('text=Create Mind Map');
      await page.click('text=Create Mind Map');
      
      // Check for validation errors
      await expect(page.locator('text=Title is required')).toBeVisible();
    });
  });

  test.describe('Mind Map Editing', () => {
    test('should open mind map for editing', async ({ page }) => {
      // Create a mind map first
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Editable Mind Map');
      await page.fill('[name="description"]', 'This mind map will be edited');
      await page.click('text=Create Mind Map');
      
      // Open for editing
      await page.click('text=Editable Mind Map');
      
      // Check if editor is open
      await expect(page.locator('text=Mind Map Editor')).toBeVisible();
    });

    test('should add nodes to mind map', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Node Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Node Test Mind Map');
      
      // Add a node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Test Node');
      await page.click('text=Add Node');
      
      // Check if node is added
      await expect(page.locator('text=Test Node')).toBeVisible();
    });

    test('should edit node content', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Edit Node Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Edit Node Mind Map');
      
      // Add a node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Original Node');
      await page.click('text=Add Node');
      
      // Edit the node
      await page.click('text=Original Node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Updated Node');
      await page.click('text=Update Node');
      
      // Check if node is updated
      await expect(page.locator('text=Updated Node')).toBeVisible();
    });

    test('should delete nodes', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Delete Node Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Delete Node Mind Map');
      
      // Add a node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Node to Delete');
      await page.click('text=Add Node');
      
      // Delete the node
      await page.click('text=Node to Delete');
      await page.click('[data-testid="delete-node"], .delete-node');
      await page.click('text=Delete');
      
      // Check if node is deleted
      await expect(page.locator('text=Node to Delete')).not.toBeVisible();
    });

    test('should add connections between nodes', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Connection Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Connection Mind Map');
      
      // Add two nodes
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Node 1');
      await page.click('text=Add Node');
      
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Node 2');
      await page.click('text=Add Node');
      
      // Connect the nodes
      await page.click('text=Node 1');
      await page.click('[data-testid="connect-node"], .connect-node');
      await page.click('text=Node 2');
      
      // Check if connection is created
      await expect(page.locator('[data-testid="connection"], .connection')).toBeVisible();
    });

    test('should change node colors', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Color Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Color Mind Map');
      
      // Add a node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Colored Node');
      await page.click('text=Add Node');
      
      // Change node color
      await page.click('text=Colored Node');
      await page.click('[data-testid="color-picker"], .color-picker');
      await page.click('[data-testid="color-red"], .color-red');
      
      // Check if color is applied
      const node = page.locator('text=Colored Node');
      await expect(node).toHaveClass(/bg-red/);
    });

    test('should add notes to nodes', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Notes Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Notes Mind Map');
      
      // Add a node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Node with Notes');
      await page.click('text=Add Node');
      
      // Add notes
      await page.click('text=Node with Notes');
      await page.click('[data-testid="add-notes"], .add-notes');
      await page.fill('[data-testid="notes-text"], textarea[placeholder*="notes"]', 'These are test notes');
      await page.click('text=Save Notes');
      
      // Check if notes are added
      await expect(page.locator('text=These are test notes')).toBeVisible();
    });
  });

  test.describe('Mind Map Visualization', () => {
    test('should display mind map in different layouts', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Layout Test Mind Map');
      await page.selectOption('[name="layout"]', 'radial');
      await page.click('text=Create Mind Map');
      await page.click('text=Layout Test Mind Map');
      
      // Check if radial layout is applied
      await expect(page.locator('[data-testid="radial-layout"], .radial-layout')).toBeVisible();
      
      // Change to hierarchical layout
      await page.click('[data-testid="layout-selector"], .layout-selector');
      await page.click('text=Hierarchical');
      
      // Check if hierarchical layout is applied
      await expect(page.locator('[data-testid="hierarchical-layout"], .hierarchical-layout')).toBeVisible();
    });

    test('should zoom in and out', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Zoom Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Zoom Test Mind Map');
      
      // Zoom in
      await page.click('[data-testid="zoom-in"], .zoom-in');
      
      // Check if zoom level increased
      const canvas = page.locator('[data-testid="mindmap-canvas"], .mindmap-canvas');
      await expect(canvas).toHaveAttribute('data-zoom', '1.2');
      
      // Zoom out
      await page.click('[data-testid="zoom-out"], .zoom-out');
      
      // Check if zoom level decreased
      await expect(canvas).toHaveAttribute('data-zoom', '1.0');
    });

    test('should pan around the mind map', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Pan Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Pan Test Mind Map');
      
      // Pan the mind map
      const canvas = page.locator('[data-testid="mindmap-canvas"], .mindmap-canvas');
      await canvas.dragTo(canvas, { targetPosition: { x: 100, y: 100 } });
      
      // Check if pan is applied
      await expect(canvas).toHaveAttribute('data-pan-x', '100');
    });

    test('should collapse and expand nodes', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Collapse Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Collapse Test Mind Map');
      
      // Add a parent node
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Parent Node');
      await page.click('text=Add Node');
      
      // Add a child node
      await page.click('text=Parent Node');
      await page.click('[data-testid="add-child"], .add-child');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Child Node');
      await page.click('text=Add Node');
      
      // Collapse parent node
      await page.click('text=Parent Node');
      await page.click('[data-testid="collapse-node"], .collapse-node');
      
      // Check if child is hidden
      await expect(page.locator('text=Child Node')).not.toBeVisible();
      
      // Expand parent node
      await page.click('text=Parent Node');
      await page.click('[data-testid="expand-node"], .expand-node');
      
      // Check if child is visible again
      await expect(page.locator('text=Child Node')).toBeVisible();
    });

    test('should search within mind map', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Search Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Search Test Mind Map');
      
      // Add nodes with different content
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Math Node');
      await page.click('text=Add Node');
      
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Science Node');
      await page.click('text=Add Node');
      
      // Search for math nodes
      await page.fill('[data-testid="search-input"], input[placeholder*="search"]', 'Math');
      await page.keyboard.press('Enter');
      
      // Check if only math node is highlighted
      await expect(page.locator('text=Math Node')).toHaveClass(/highlighted/);
      await expect(page.locator('text=Science Node')).not.toHaveClass(/highlighted/);
    });
  });

  test.describe('Mind Map Management', () => {
    test('should save mind map automatically', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Auto Save Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Auto Save Mind Map');
      
      // Make changes
      await page.click('[data-testid="add-node"], .add-node');
      await page.fill('[data-testid="node-text"], input[placeholder*="node"]', 'Auto Saved Node');
      await page.click('text=Add Node');
      
      // Wait for auto-save
      await page.waitForTimeout(2000);
      
      // Refresh page
      await page.reload();
      
      // Check if changes are preserved
      await expect(page.locator('text=Auto Saved Node')).toBeVisible();
    });

    test('should export mind map', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Export Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Export Test Mind Map');
      
      // Export as image
      await page.click('[data-testid="export-button"], .export-button');
      await page.click('text=Export as Image');
      
      // Check if download starts
      const downloadPromise = page.waitForEvent('download');
      await page.click('text=Download');
      const download = await downloadPromise;
      
      expect(download.suggestedFilename()).toContain('Export Test Mind Map');
    });

    test('should share mind map', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Share Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Share Test Mind Map');
      
      // Share the mind map
      await page.click('[data-testid="share-button"], .share-button');
      
      // Check if share options are visible
      await expect(page.locator('text=Share Link')).toBeVisible();
      await expect(page.locator('text=Copy Link')).toBeVisible();
    });

    test('should delete mind map', async ({ page }) => {
      // Create a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Delete Test Mind Map');
      await page.click('text=Create Mind Map');
      
      // Delete the mind map
      await page.click('[data-testid="delete-mindmap"], .delete-mindmap');
      await page.click('text=Delete');
      
      // Check if mind map is deleted
      await expect(page.locator('text=Delete Test Mind Map')).not.toBeVisible();
    });
  });

  test.describe('Collaboration', () => {
    test('should invite collaborators', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Collaboration Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Collaboration Test Mind Map');
      
      // Invite collaborator
      await page.click('[data-testid="invite-button"], .invite-button');
      await page.fill('[name="email"]', 'collaborator@example.com');
      await page.click('text=Send Invitation');
      
      // Check if invitation is sent
      await expect(page.locator('text=Invitation sent')).toBeVisible();
    });

    test('should show real-time updates', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Real-time Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Real-time Test Mind Map');
      
      // Check for real-time indicators
      await expect(page.locator('[data-testid="online-indicator"], .online-indicator')).toBeVisible();
    });
  });

  test.describe('Accessibility', () => {
    test('should support keyboard navigation', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Accessibility Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Accessibility Test Mind Map');
      
      // Navigate with keyboard
      await page.keyboard.press('Tab');
      await page.keyboard.press('Enter'); // Should add a node
      
      // Check if node is added
      await expect(page.locator('[data-testid="node"], .node')).toBeVisible();
    });

    test('should have proper ARIA labels', async ({ page }) => {
      // Check for ARIA labels on interactive elements
      const createButton = page.locator('text=Create Mind Map');
      await expect(createButton).toHaveAttribute('aria-label');
    });

    test('should support screen readers', async ({ page }) => {
      // Check for screen reader friendly elements
      await expect(page.locator('[role="main"]')).toBeVisible();
      await expect(page.locator('[role="complementary"]')).toBeVisible();
    });
  });

  test.describe('Performance', () => {
    test('should load quickly', async ({ page }) => {
      const startTime = Date.now();
      
      await page.goto('/tools/mind-maps');
      
      const loadTime = Date.now() - startTime;
      expect(loadTime).toBeLessThan(3000); // Should load within 3 seconds
    });

    test('should handle large mind maps', async ({ page }) => {
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Large Mind Map Test');
      await page.click('text=Create Mind Map');
      await page.click('text=Large Mind Map Test');
      
      // Add many nodes
      for (let i = 1; i <= 20; i++) {
        await page.click('[data-testid="add-node"], .add-node');
        await page.fill('[data-testid="node-text"], input[placeholder*="node"]', `Node ${i}`);
        await page.click('text=Add Node');
        await page.waitForTimeout(100); // Small delay
      }
      
      // Check if all nodes are displayed
      for (let i = 1; i <= 20; i++) {
        await expect(page.locator(`text=Node ${i}`)).toBeVisible();
      }
    });
  });

  test.describe('Error Handling', () => {
    test('should handle save errors', async ({ page }) => {
      // Mock save error
      await page.route('**/api/mindmaps/**', route => {
        route.fulfill({
          status: 500,
          body: JSON.stringify({ error: 'Save failed' })
        });
      });
      
      // Create and open a mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Error Test Mind Map');
      await page.click('text=Create Mind Map');
      await page.click('text=Error Test Mind Map');
      
      // Try to save
      await page.click('[data-testid="save-button"], .save-button');
      
      // Check for error message
      await expect(page.locator('text=Save failed')).toBeVisible();
    });

    test('should handle network errors', async ({ page }) => {
      // Mock network error
      await page.route('**/api/mindmaps/**', route => {
        route.abort('failed');
      });
      
      // Try to create mind map
      await page.click('text=Create Mind Map');
      await page.fill('[name="title"]', 'Network Error Test');
      await page.click('text=Create Mind Map');
      
      // Check for error message
      await expect(page.locator('text=Network error')).toBeVisible();
    });
  });
}); 